### ISSUE TITLE
Post-processing of the detections

### ISSUE THREAD

**Issue by rahman-mdatiqur** [HYPJUDY/Decouple-SSAD#12]
Hello @HYPJUDY ,

For post-processing the detections, you seem to be using the top-3 predictions for each class in the function [post_process](https://github.com/HYPJUDY/Decouple-SSAD/blob/master/operations.py#L369), whereas, in the activity detection literature including the original SSAD paper, only the top prediction is used. 

Can you please provide some insights about choosing the top-3 predictions? Do you also do the same for ActivityNet dataset?

I would highly appreciate your response.
Thanks.

**Comment by HYPJUDY** [comment]
Hi, I refer this post processing tip/trick from another action detection code repository (but sorry I forgot which one, I should have written a comment... it should be a public code repo with paper published in recent 2~3 years).
I didn't highlight this operation because as I commented here
https://github.com/HYPJUDY/Decouple-SSAD/blob/9a78cea6be27f9cc7cd512e027f00526be5ecad8/operations.py#L410
It didn't improve the performance a lot, especially when doing this operation more than twice, and it cost more time.
You can try to remove this operation and compare the performance.

**Comment by rahman-mdatiqur** [comment]
Hello @HYPJUDY 
thanks for the reply. Yes, you are right in saying that performance does not vary much. I just used the top-1 predictions and the difference is about 0.7 mAP.
