### ISSUE TITLE
Using different dataset

### ISSUE THREAD

**Issue by sanjitjain2** [HYPJUDY/Decouple-SSAD#6]
How do I use this on my own dataset?

**Comment by HYPJUDY** [comment]
You may [Preprocess Data by Yourself](https://github.com/HYPJUDY/Decouple-SSAD/blob/master/data/README.md#preprocess-data-by-yourself) and them train and test models following the process in [run-code session](https://github.com/HYPJUDY/Decouple-SSAD#run-code).

**Comment by sanjitjain2** [comment]
Can you explain more about training the Base Feature Network as my dataset is different and I cannot use the pretrained weights as mentioned. Thanks in advance.

**Comment by HYPJUDY** [comment]
Since the input features have gone through big network like ResNet and pretrained on other datasets (e.g., UCF101 or Kinetics), they contain many informations. The Base Feature Network is mainly used to shorten the temporal length of feature map and increase the size of receptive fields, which do not need very complex design.
I adopt the design of [Conv-pool-Conv-pool](https://github.com/HYPJUDY/Decouple-SSAD/blob/8af4bfd5840c6403f7cc4b6cea2ea328db30498e/operations.py#L227) similar to [Single Shot Temporal Action Detection](https://arxiv.org/abs/1710.06236).
You can refer to the Section 4.4 Architectures of SSAD network for more details.
